# Build image
# `docker-compose -f docker-compose.yml build`
# Push to registry
# `docker-compose -f docker-compose.yml push`

version: '3.7'

services:
  app:
    image: registry.lts.harvard.edu/lts/curiosity:2.7.0-lts-4
    build:
      context: .
      dockerfile: Dockerfile